CELL_DIAMETER = 0.08

CELLS_DIAMETERS_FILE_NAME = 'cells_diameters.txt'
ELEMENTS_FILE_NAME = 'elements.txt'

NET_DIMENSIONS = {
    'x1': -2,
    'y1': -2,
    'x2': 2,
    'y2': 2
}

ORIGIN_COORDINATES = {
    'x': 0,
    'y': 0
}

QUANTIFICATION_WINDOW_WIDTH_IN_CELL_DIAMETER = 1
QUANTIFICATION_WINDOW_HEIGHT_IN_CELL_DIAMETER = 1
EPSILON = 1.0e-8
